version: 3.20.2
name: Inkdrop
notes: |
  ## v3.20.2
  * **bugfix**: Version dialog not shown on Windows or Linux (Thanks Sceptic)
  * **bugfix**: The app won't quit immediately in some case (Thanks Sceptic)
  * **bugfix**: Plugin keybindings not shown correctly on the preference screen (Thanks [Samantha](https://forum.inkdrop.info/t/enable-codefold/407/24))
  * **bugfix**: Prohibit deleting default notebook (Thanks Sceptic)
  * **bugfix**: Avoid overwriting notes with same title and date time when exporting (Thanks Sceptic)
  * **bugfix**: Hide editor search box when toggling preview (Thanks [Vianney](https://forum.inkdrop.info/t/search-tool-breaks-the-notes-header/473))
  * **bugfix**: Allow file:// protocol for images (Thanks [Sceptic](https://forum.inkdrop.info/t/pdf-links-break-the-window-its-openend-in/593/2))

  ## v3.20.1
  * **improvement**: Change the label for removing note from 'Delete' to 'Move to Trash' (Thanks [Dan](https://forum.inkdrop.info/t/add-a-confirmation-prompt-when-deleting-notes/457))
  * **improvement**: Exporting with preview theme styling (Thanks [audiosyncrasy](https://forum.inkdrop.info/t/pdf-export-with-preview-theme-styling/489))
  * **improvement**: Allow rendering `<mark>` tag (Thanks [Hoopy](https://forum.inkdrop.info/t/plugin-dev-extending-markdown-syntax/427))

  ## v3.20.0
  * **bugfix**: Fixed a problem where the sync requests always time out after 10 seconds. It sometimes causes to fail synchronization when you have a lot of notes and images to sync at once (Thanks [Hoopy](https://forum.inkdrop.info/t/recommended-setup-for-own-sync-server/374/13))
  * **bugfix**: Use 20 characters for indexing notes with title (Thanks chocolat)
  * **bugfix**: Handle `mailto:` links properly (Thanks [Samantha](https://forum.inkdrop.info/t/how-to-make-mailto-links-work/409))
  * **improvement**: Add logout and sync menu (Thanks [Al and Bob](https://forum.inkdrop.info/t/how-to-logout-switch-accounts/401/3))
  * **improvement**: Stop checking update once it found new version on Linux (Thanks [Luis, Parker and Al](https://forum.inkdrop.info/t/how-can-i-disable-the-update-popup/388/4))
  * **improvement**: Select all text on focus on the search bar (Thanks [Jesse and Robert](https://forum.inkdrop.info/t/feature-refinement-remove-search-context-from-ui-for-regular-searches-use-tagname-for-tag-filters/357))

  ## v3.19.0
  * **improvement**: Add print shortcut for windows and linux (Thanks Otawara-san)
  * **improvement**: Show native traffic light window buttons on macOS (Thanks [Dan](https://forum.inkdrop.info/t/macos-traffic-light-window-buttons-dont-behave-as-expected/340))
  * **improvement**: Better keychain error message
  * **improvement**: New config for sync: `core.db.sync.options` (Thanks [Hoopy](https://forum.inkdrop.info/t/recommended-setup-for-own-sync-server/375))
  * **bugfix**: Ignore case for title sort (Thanks [Florian](https://forum.inkdrop.info/t/inkdrop-should-ignore-case-when-ordering-note-lists-by-title/385))

  ## v3.18.0
  * **New feature**: Exporting individual notes (Thanks, [Takeuchi-san](https://forum.inkdrop.info/t/export-selected-notes-as-markdown/253))
  * **Improvement**: Support changing sort mode via commands:
    - `view:sort-by-title`
    - `view:sort-by-date-created`
    - `view:sort-by-date-updated`
    - `view:sort-in-ascending`
    - `view:sort-in-descending`
  * **Improvement**: Don't save the window state if it's fullscreen/maximized (Thanks, [Otawara-san](https://forum.inkdrop.info/t/windows/287))
  * **Bugfix**: Syntax highlighting for PHP won't work (Thanks, [Nick](https://forum.inkdrop.info/t/php-highlighting-doesn-t-work-is-it-only-me-or/301) and [Kagaya-san](https://forum.inkdrop.info/t/php/266))
  * **Bugfix**: Avoid duplicate keybinding for cmd-u & ctrl-u (Thanks, [Otawara-san](https://forum.inkdrop.info/t/ctrl-u/283/4))

  ## v3.17.4
  * **Bugfix**: It always fails to initialize `solarized-light-syntax` plugin
  * **Improvement**: A little bit faster app initialization

  ## v3.17.3
  * **Bugfix**: Toggling task-list isn't working
  * **Improvement**: Drop paste-as-markdown support. Use [paste-as-markdown plugin](https://app.inkdrop.info/plugins/paste-as-markdown) instead.
  * **Improvement**: Drop support for auto-incrementing list numbers when typed return key. Use [autoupdate-list-numbers plugin](https://app.inkdrop.info/plugins/autoupdate-list-numbers) instead.
  * **Improvement**: Better conversion from HTML to Markdown
  * [Learn more](https://community.inkdrop.info/note/d975606d93c067c5ef8d6adfb5db83b5/note:HylTjpE9zz)

  ## v3.17.2
  * **Bugfix**: The account status won't be recognized correctly when it is not active (e.g., trial expired)

  ## v3.17.1
  * **Improvement**: Show helpful guide on the login failures
  * **Bugfix**: "Add Notebook" button on the side bar doesn't work (Thanks, Nitawaki-san)

  ## v3.17.0
  * **New feature**: Showing invisible characters (Thanks, Kato-san)
  * **Improvement**: Open up the download page when new version available but not using auto update (Thanks, [Aleksandar](https://forum.inkdrop.info/t/recognize-the-proper-installation-method-when-offering-an-update-link))
  * **Improvement**: Start syncing automatically when network is back online
  * **Improvement**: Show detailed error message when failed logging in
  * **Improvement**: Cursor moves to the next placeholder when executed `Insert Link` while selecting text (Thanks, Nitawaki-san)
  * **Bugfix**: Auto-increment for numbered lists corrupts mixed-type list (Thanks, Nitawaki-san)
pub_date: 2018-07-21T07:46:52.174Z
files:
  darwin:
    archive: Inkdrop-3.20.2-Mac.zip
  win32:
    archive: Inkdrop-3.20.2-Windows.zip
    installer: Setup.exe
    nupkg: inkdrop-3.20.2-full.nupkg
    releases: RELEASES
  linux:
    archive: Inkdrop-3.20.2-Linux.zip
    deb: inkdrop_3.20.2_amd64.deb
    rpm: inkdrop-3.20.2.x86_64.rpm
